Update Dockerfile , Python, and R installation scripts for improved package management and dependencies. Python updated to 3.14.4 and R updated to 4.5.2

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -5,13 +5,14 @@
 # Stage 1: Build Python with --enable-shared
 FROM ubuntu:jammy AS python-builder
 
-ARG PYTHON_VERSION=3.14.4
-ARG PYTHON_URL=https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz
+ARG PYTHON_MAJOR_VERSION=3.14
+ARG PYTHON_FULL_VERSION=${PYTHON_MAJOR_VERSION}.4
+ARG PYTHON_URL=https://www.python.org/ftp/python/${PYTHON_FULL_VERSION}/Python-${PYTHON_FULL_VERSION}.tar.xz
 
 # Install build dependencies
 RUN apt-get -qq update \
   && DEBIAN_FRONTEND="noninteractive" apt -qq install -y --no-install-recommends \
-  ca-certificates \
+  apache2-dev \
   libffi-dev \
   libsqlite3-dev \
   libreadline-dev \
@@ -20,10 +21,28 @@ RUN apt-get -qq update \
   tk-dev \
   libgdbm-dev \
   libc6-dev \
+  liblzma-dev \
   libbz2-dev \
   zlib1g-dev \
+  libpng-dev \
+  libtiff5-dev \
+  libjpeg-dev \
+  libblosc-dev \
+  libhdf5-dev \
+  hdf5-helpers \
+  hdf5-tools \
+  libblas-dev \
+  liblapack-dev \
+  libcairo2-dev \
+  libxml2-dev \
+  libwebp-dev \
+  ca-certificates \
   wget \
-  build-essential \
+  gcc \
+  g++ \
+  make \
+  pkg-config \
+  git \
   && apt -qq clean autoclean \
   && apt -qq autoremove -y \
   && rm -rf /var/lib/apt/lists/*
@@ -32,100 +51,130 @@ RUN apt-get -qq update \
 # --enable-shared is needed due to the Apache mod_wsgi module needing to link against the Python shared library.
 WORKDIR /tmp
 RUN wget $PYTHON_URL \
-  && tar -xf Python-${PYTHON_VERSION}.tar.xz \
-  && cd Python-${PYTHON_VERSION} \
-  && ./configure --prefix=/opt/Python-${PYTHON_VERSION} --enable-optimizations --enable-shared \
+  && tar -xf Python-${PYTHON_FULL_VERSION}.tar.xz \
+  && cd Python-${PYTHON_FULL_VERSION} \
+  # LDFLAGS, CPPFLAGS, and PKG_CONFIG_PATH are needed to ensure the build process can find the lzma library and headers,
+  # which are required for Python's lzma module.  Without these flags, the build process may fail to find lzma downstream.
+  && ./configure --prefix=/opt/Python-${PYTHON_FULL_VERSION} --enable-optimizations --enable-shared \
+    LDFLAGS="-L/usr/lib/x86_64-linux-gnu" \
+    CPPFLAGS="-I/usr/include" \
+    PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig" \
   && make install \
   && cd /tmp \
-  && rm -rf Python-${PYTHON_VERSION}*
+  && rm -rf Python-${PYTHON_FULL_VERSION}*
 
-# Stage 2: Install R packages (using Bioconductor base image)
-FROM bioconductor/bioconductor_docker:3.21-r-4.5.2 AS r-builder
+# Upgrade pip and install requirements from file
+# This set of modules will be used by the main Python install and scripts that call it (like CGI ones)
+# numpy is installed before requirements.txt because of dependency requirement issues
+# NOTE: Installing custom version of diffxpy that is based on the latest commit on the main branch (at the time)
+WORKDIR /opt/Python-${PYTHON_FULL_VERSION}/bin
+COPY ./requirements.txt /opt/gEAR/docker/requirements.txt
 
-# Install additional runtime dependencies if needed
+ENV LD_LIBRARY_PATH="/opt/Python-${PYTHON_FULL_VERSION}/lib"
+
+# Disable user-installs to guarantee packages go into /opt/Python...
+ENV PIP_USER=0
+
+# Install stuff
+RUN ./python3 -m pip install --upgrade pip setuptools wheel \
+  && ./python3 -m pip install -r /opt/gEAR/docker/requirements.txt --prefer-binary \
+  && ./python3 -m pip uninstall dask-expr -y
+
+# Cleanup
+RUN chmod 777 /opt/Python-${PYTHON_FULL_VERSION}/lib/python${PYTHON_MAJOR_VERSION}/site-packages/scanpy/preprocessing/__pycache__ 2>/dev/null || true \
+  && rm -rf ~/.cache/pip
+
+
+# Stage 2: Install R packages using shell scirpts
+FROM ubuntu:jammy AS r-builder
+
+# originally used a bioconductor base image, but ran into an issue where
+# the base image was using ubuntu:24.04 (instead of 22:04)
+# which could cause gcc compiler issues in stage 3
+
+# 1. Install required system dependencies for compiling R and packages
 RUN apt-get -qq update \
   && DEBIAN_FRONTEND="noninteractive" apt -qq install -y --no-install-recommends \
-  ca-certificates \
   curl \
-  # to build rpy2
-  python3-pip \
+  wget \
   build-essential \
+  gfortran \
+  libreadline-dev \
+  xorg-dev \
+  libbz2-dev \
+  libcurl4-openssl-dev \
+  libssl-dev \
+  libxml2-dev \
+  libfontconfig1-dev \
+  libharfbuzz-dev \
+  libfribidi-dev \
+  libfreetype6-dev \
+  libpng-dev \
+  libtiff5-dev \
+  libjpeg-dev \
+  libwebp-dev \
+  libgit2-dev \
+  libuv1-dev \
+  ca-certificates \
+  tzdata \
+  git \
+  unzip \
   && apt -qq clean autoclean \
   && apt -qq autoremove -y \
   && rm -rf /var/lib/apt/lists/*
 
-# Copy install scripts
-COPY ./install_packages.R /tmp/
+# 2. Install Bioconductor
+WORKDIR /opt/gEAR/docker
+COPY ./install_bioc.sh ./install_bioc.R ./
+RUN chmod +x install_bioc.sh \
+  && ./install_bioc.sh
 
-# Install R packages
-RUN /usr/local/bin/Rscript --vanilla /tmp/install_packages.R || exit 1
+# 3. Install other packages
+COPY ./install_packages.R ./
+RUN Rscript --vanilla install_packages.R || exit 1
 
-# Pre-build rpy2 wheel
-RUN pip3 wheel --no-cache-dir --no-deps --wheel-dir /tmp/wheels rpy2==3.6.7
 
 # Stage 3: Final runtime image
-FROM ubuntu:jammy
+FROM ubuntu:jammy AS final
 
 ARG TARGETARCH
 # Some package building issues when attempting to use 3.14
 ARG PYTHON_MAJOR_VERSION=3.14
 ARG PYTHON_FULL_VERSION=${PYTHON_MAJOR_VERSION}.4
-ARG CMAKE_VERSION=3.19.8
-ARG CMAKE_URL=https://github.com/Kitware/CMake/archive/refs/tags/v${CMAKE_VERSION}.tar.gz
 ARG GEAR_URL=https://www.github.com/IGS/gEAR.git
 ARG GEAR_BRANCH=devel
 
-# For pybigwig dependency
-ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
-
+LABEL author="Shaun Adkins <sadkins@som.umaryland.edu>"
 LABEL maintainer="Shaun Adkins <sadkins@som.umaryland.edu>"
 
 # Install runtime packages
 RUN apt-get -qq update \
   && DEBIAN_FRONTEND="noninteractive" apt -qq install -y --no-install-recommends \
-  gcc \
-  g++ \
-  make \
-  libffi-dev \
-  libsqlite3-dev \
-  libhdf5-dev \
-  libreadline-dev \
-  libncursesw5-dev \
-  libssl-dev \
-  tk-dev \
-  libgdbm-dev \
-  libc6-dev \
-  libbz2-dev \
-  hdf5-helpers \
-  hdf5-tools \
-  zlib1g-dev \
-  libblas-dev \
-  liblapack-dev \
-  libcairo2-dev \
-  libxml2-dev \
-  libhdf5-serial-dev \
-  libwebp-dev \
   ca-certificates \
   curl \
+  make \
+  gcc \
+  g++ \
   rsync \
   wget \
   git \
   vim \
   unzip \
   llvm \
-  libharfbuzz-dev \
-  libfribidi-dev \
-  libfreetype6-dev \
-  libgit2-dev \
-  libpng-dev \
-  libtiff5-dev \
-  libjpeg-dev \
-  libblosc-dev \
-  apache2-dev \
   apache2 \
   php \
+  libffi-dev \
+  libpcre2-dev \
+  zlib1g-dev \
+  libbz2-dev \
+  liblzma-dev \
+  libicu-dev \
+  libdeflate-dev \
+  libssl3 \
   libapache2-mod-php \
   php-gd \
+  libffi-dev \
+  libpcre2-dev \
   && apt -qq clean autoclean \
   && apt -qq autoremove -y \
   && rm -rf /var/lib/apt/lists/*
@@ -138,18 +187,29 @@ COPY --from=python-builder /opt/Python-${PYTHON_FULL_VERSION} /opt/Python-${PYTH
 # Copy compiled R from r-builder stage
 COPY --from=r-builder /usr/local/lib/R /usr/local/lib/R
 
-# Copy pre-built rpy2 wheel
-COPY --from=r-builder /tmp/wheels /tmp/wheels
-
-
 # Link Python and shared library
 RUN mkdir -p /opt/bin \
   && ln -s /opt/Python-${PYTHON_FULL_VERSION}/bin/python3 /opt/bin/python3 \
-  && ln -s /opt/Python-${PYTHON_FULL_VERSION}/lib/libpython3.14.so.1.0 /usr/lib/
+  && ln -s /opt/Python-${PYTHON_FULL_VERSION}/lib/libpython${PYTHON_MAJOR_VERSION}.so.1.0 /usr/lib/
 
-# LD_LIBRARY_PATH needs R library path for rpy2 compatibility
-ENV LD_LIBRARY_PATH="/usr/local/lib/R/lib"
+# Tell the system linker about the new Python libs
+RUN echo "/opt/Python-${PYTHON_FULL_VERSION}/lib" > /etc/ld.so.conf.d/python314.conf \
+    && ldconfig
+
+# LD_LIBRARY_PATH needs R library path for rpy2 compatibility and Python library path too
+ENV LD_LIBRARY_PATH="/usr/local/lib/R/lib:/opt/Python-${PYTHON_FULL_VERSION}/lib"
 ENV R_HOME="/usr/local/lib/R"
+ENV PATH="/opt/Python-${PYTHON_FULL_VERSION}/bin:/usr/local/lib/R/bin:${PATH}"
+
+# Force GCC 11 to use a newer C standard to understand R 4.5.2 headers
+ENV CFLAGS="-std=gnu2x"
+
+# Install rpy2 now that R has installed
+RUN /opt/bin/python3 -m pip install rpy2==3.6.7
+
+# Pre-compile all Python bytecode during the build so Apache doesn't try to write it at runtime
+#RUN /opt/Python-${PYTHON_FULL_VERSION}/bin/python3 -m compileall -q /opt/Python-${PYTHON_FULL_VERSION}/lib/python${PYTHON_MAJOR_VERSION}/site-packages/
+RUN find /opt/Python-${PYTHON_FULL_VERSION}/lib/python${PYTHON_MAJOR_VERSION}/site-packages/ -name __pycache__ -exec chmod 777 {} \;
 
 # Get gEAR code.  Currently cannot do a git clone by normal means due to the repo being "private"
 WORKDIR /opt
@@ -158,22 +218,6 @@ RUN git clone -b ${GEAR_BRANCH} --single-branch ${GEAR_URL} \
   && ln -s /opt/gEAR/www/ /var/
 
 COPY ./gear.ini.docker /opt/gEAR/gear.ini
-
-# Upgrade pip and install requirements from file
-# This set of modules will be used by the main Python install and scripts that call it (like CGI ones)
-# numpy is installed before requirements.txt because of dependency requirement issues
-# NOTE: Installing custom version of diffxpy that is based on the latest commit on the main branch (at the time)
-WORKDIR /opt/Python-${PYTHON_FULL_VERSION}/bin
-COPY ./requirements.txt /opt/gEAR/docker/requirements.txt
-RUN ./pip3 install --upgrade pip setuptools wheel \
-  # Ran into "error: resolution-too-deep" so used `pip freeze` from a production env to create requirements.full.txt
-  # Source: https://medium.com/@ebenyemiriam17/error-resolution-too-deep-how-i-fixed-my-pip-dependency-resolution-error-9cb3471344f9
-  && ./pip3 install -r /opt/gEAR/docker/requirements.txt  --prefer-binary \
-  # Uninstall dask-expr to avoid issues with spatialdata (https://github.com/scverse/spatialdata/pull/570)
-  && ./pip3 uninstall dask-expr -y \
-  && (chmod 777 /opt/Python-${PYTHON_FULL_VERSION}/lib/python${PYTHON_MAJOR_VERSION}/site-packages/scanpy/preprocessing/__pycache__ || true) \
-  && rm -rf ~/.cache/pip \
-  && find /opt/Python-${PYTHON_FULL_VERSION} -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
 
 # Apache things
 WORKDIR /opt/gEAR
